#!/bin/bash

## To use this hook execute in the project root:
## git config --local core.hooksPath .githooks/
if npm run lint; then
    npx hardhat compile --force
    npm run docgen
    git add docs
    cp artifacts/contracts/PolygonZKEVMBridge.sol/PolygonZKEVMBridge.json compiled-contracts/
    cp artifacts/contracts/PolygonZKEVMGlobalExitRoot.sol/PolygonZKEVMGlobalExitRoot.json compiled-contracts/
    cp artifacts/contracts/PolygonZKEVMGlobalExitRootL2.sol/PolygonZKEVMGlobalExitRootL2.json compiled-contracts/
    cp artifacts/contracts/lib/TokenWrapped.sol/TokenWrapped.json compiled-contracts/
    cp artifacts/contracts/mocks/PolygonZKEVMBridgeMock.sol/PolygonZKEVMBridgeMock.json compiled-contracts/
    cp artifacts/contracts/mocks/ERC20PermitMock.sol/ERC20PermitMock.json compiled-contracts/
    cp artifacts/contracts/mocks/PolygonZKEVMGlobalExitRootL2Mock.sol/PolygonZKEVMGlobalExitRootL2Mock.json compiled-contracts/
    cp artifacts/contracts/mocks/PolygonZKEVMGlobalExitRootMock.sol/PolygonZKEVMGlobalExitRootMock.json compiled-contracts/
    cp artifacts/contracts/mocks/PolygonZKEVMMock.sol/PolygonZKEVMMock.json compiled-contracts/
    cp artifacts/contracts/mocks/VerifierRollupHelperMock.sol/VerifierRollupHelperMock.json compiled-contracts/
    cp artifacts/contracts/PolygonZKEVM.sol/PolygonZKEVM.json compiled-contracts/
    cp artifacts/contracts/verifiers/Verifier.sol/Verifier.json compiled-contracts/
    git add compiled-contracts
    exit 0
else
    exit 1
fi

