FROM ethereum/client-go

EXPOSE 8545

RUN ls
COPY docker/gethData /


ENTRYPOINT ["geth"]
CMD ["--http", "--http.addr", "0.0.0.0","--http.corsdomain", "*", "--http.vhosts" ,"*", "--ws", "--ws.origins", "*", "--ws.addr", "0.0.0.0", "--dev", "--datadir", "/geth_data"]