/* eslint-disable no-await-in-loop, no-use-before-define, no-lonely-if */
/* eslint-disable no-console, no-inner-declarations, no-undef, import/no-unresolved */
import { expect } from 'chai';
import path = require('path');
import fs = require('fs');
import { ethers, upgrades } from 'hardhat';
import * as dotenv from 'dotenv';
import { logger } from '../../src/logger';
import { TimelockController } from '../../typechain-types';
import { genTimelockOperation, decodeScheduleData } from '../utils';
import { checkParams, getDeployerFromParameters, getProviderAdjustingMultiplierGas } from '../../src/utils';

import upgradeParameters from './upgrade_parameters.json';
import { addInfoOutput } from '../../tools/utils';
import { getLBTData } from '../../tools/getLBT/getLBT';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const pathOutputJson = path.join(__dirname, './upgrade_output.json');

const NEW_GER_L2 = 'AgglayerGERL2';
const NEW_BRIDGE_L2 = 'AgglayerBridgeL2FromEtrog';

async function main() {
    // Check for unsafe mode from parameters
    const isUnsafeMode = (upgradeParameters as any).unsafeMode || false;
    if (isUnsafeMode) {
        logger.warn('⚠️  UNSAFE MODE ENABLED: criticalTooling checks disabled');
    }

    let outputJson = {};
    // Add git info using addInfoOutput with criticalTooling flag
    outputJson = addInfoOutput(outputJson, !isUnsafeMode);

    /*
     * Check upgrade parameters
     * Check that every necessary parameter is fulfilled
     */
    const mandatoryUpgradeParameters = [
        'bridgeL2Address',
        'bridge_initParams.bridgeManager',
        'bridge_initParams.proxiedTokensManagerAddress',
        'bridge_initParams.emergencyBridgePauserAddress',
        'bridge_initParams.emergencyBridgeUnpauserAddress',
        'ger_initParams.globalExitRootUpdater',
        'ger_initParams.globalExitRootRemover',
    ];
    checkParams(upgradeParameters, mandatoryUpgradeParameters);

    const salt = (upgradeParameters as any).timelockSalt || ethers.ZeroHash;
    const { bridgeL2Address, pathTokensJson } = upgradeParameters as any;
    const { bridgeManager, proxiedTokensManagerAddress, emergencyBridgePauserAddress, emergencyBridgeUnpauserAddress } =
        upgradeParameters.bridge_initParams;
    const { globalExitRootUpdater, globalExitRootRemover } = upgradeParameters.ger_initParams;

    // Load provider
    const currentProvider = getProviderAdjustingMultiplierGas(upgradeParameters, ethers);

    // Get tokens data: either from file or by fetching LBT data directly
    let initNativeSupply: string;
    let tokenAddresses: string[];

    if (pathTokensJson) {
        // Read tokens.json file (object with initNativeSupply and tokenAddresses)
        // This file is generated by tools/getLBT/getLBT.ts with printTokens: true option
        logger.info(`Loading tokens data from file: ${pathTokensJson}`);
        const finalPath = path.join(__dirname, `${pathTokensJson}`);
        const tokensData = JSON.parse(fs.readFileSync(finalPath, 'utf8'));

        // Validate tokens.json format
        if (!tokensData.initNativeSupply || !tokensData.tokenAddresses) {
            throw new Error(
                'Invalid tokens.json format. Expected object with initNativeSupply and tokenAddresses fields.',
            );
        }

        initNativeSupply = tokensData.initNativeSupply;
        tokenAddresses = tokensData.tokenAddresses;
    } else {
        // Fetch LBT data directly from the bridge contract
        logger.info('No pathTokensJson provided, fetching LBT data directly from bridge contract...');
        const lbtResult = await getLBTData(currentProvider, bridgeL2Address);
        initNativeSupply = lbtResult.initNativeSupply;
        tokenAddresses = lbtResult.tokenAddresses;
        logger.info(`Fetched ${tokenAddresses.length} token addresses and initNativeSupply: ${initNativeSupply}`);

        // Save fetched data to files
        const tokensOutputPath = path.join(__dirname, 'tokens.json');
        const lbtOutputPath = path.join(__dirname, 'LBT.json');

        const tokensOutput = {
            initNativeSupply: lbtResult.initNativeSupply,
            tokenAddresses: lbtResult.tokenAddresses,
        };
        fs.writeFileSync(tokensOutputPath, JSON.stringify(tokensOutput, null, 2));
        logger.info(`Tokens data saved to: ${tokensOutputPath}`);

        fs.writeFileSync(lbtOutputPath, JSON.stringify(lbtResult.LBTObject, null, 2));
        logger.info(`LBT data saved to: ${lbtOutputPath}`);
    }

    // Load deployer
    const deployer = await getDeployerFromParameters(currentProvider, upgradeParameters, ethers);
    logger.info(`Deploying implementation with: ${deployer.address}`);

    // get proxy admin and timelock
    logger.info('Get proxy admin information');
    // Get proxy admin
    const proxyAdmin = await upgrades.admin.getInstance();

    const newBridgeFactory = await ethers.getContractFactory(NEW_BRIDGE_L2, deployer);

    // get GER from bridgeL2 using the old contract interface
    const oldBridgeFactory = await ethers.getContractFactory('PolygonZkEVMBridgeV2Pessimistic', deployer);
    const oldBridgeL2Contract = (await oldBridgeFactory.attach(bridgeL2Address)) as any;
    const gerL2Address = await oldBridgeL2Contract.globalExitRootManager();

    // Assert correct version: check that BASE_INIT_BYTECODE_WRAPPED_TOKEN does not revert on bridge
    try {
        await oldBridgeL2Contract.BASE_INIT_BYTECODE_WRAPPED_TOKEN();
    } catch (e: any) {
        throw new Error(
            `Bridge contract does not have BASE_INIT_BYTECODE_WRAPPED_TOKEN. This upgrade requires PolygonZkEVMBridgeV2 (Etrog) version. Error: ${e.message}`,
        );
    }

    // Assert correct admin
    expect(await upgrades.erc1967.getAdminAddress(gerL2Address)).to.be.equal(proxyAdmin.target);
    expect(await upgrades.erc1967.getAdminAddress(bridgeL2Address as string)).to.be.equal(proxyAdmin.target);

    const timelockAddress = await proxyAdmin.owner();

    // load timelock
    const timelockContractFactory = await ethers.getContractFactory('PolygonZkEVMTimelock', deployer);
    const timelockContract = (await timelockContractFactory.attach(timelockAddress)) as TimelockController;
    // take params delay, or minimum timelock delay
    const timelockDelay = (upgradeParameters as any).timelockDelay || (await timelockContract.getMinDelay());

    // Upgrade AgglayerBridge -> AgglayerBridgeL2FromEtrog
    const impBridge = await upgrades.prepareUpgrade(bridgeL2Address, newBridgeFactory, {
        unsafeAllow: ['constructor', 'missing-initializer', 'missing-initializer-call'],
    });

    logger.info('#######################\n');
    logger.info(`Polygon sovereign bridge implementation deployed at: ${impBridge}`);

    // Upgrade AgglayerGER --> AgglayerGERL2
    const newGerFactory = await ethers.getContractFactory(NEW_GER_L2, deployer);
    const impGER = await upgrades.prepareUpgrade(gerL2Address, newGerFactory, {
        unsafeAllow: ['constructor', 'missing-initializer', 'missing-initializer-call'],
        constructorArgs: [bridgeL2Address],
    });

    logger.info(`Polygon sovereign GER implementation deployed at: ${impGER}`);

    // Create schedule and execute operation
    logger.info('Create schedule and execute operation');
    logger.info('Operation Bridge');

    const operationBridge = genTimelockOperation(
        proxyAdmin.target,
        0, // value
        proxyAdmin.interface.encodeFunctionData('upgradeAndCall', [
            bridgeL2Address,
            impBridge,
            newBridgeFactory.interface.encodeFunctionData(
                'initializeFromEtrog(address,address,address,address,address[],uint128)',
                [
                    bridgeManager,
                    emergencyBridgePauserAddress,
                    emergencyBridgeUnpauserAddress,
                    proxiedTokensManagerAddress,
                    tokenAddresses,
                    initNativeSupply,
                ],
            ),
        ]), // data
        ethers.ZeroHash, // predecessor
        salt, // salt
    );
    logger.info('Operation GER');
    const operationGER = genTimelockOperation(
        proxyAdmin.target,
        0, // value
        proxyAdmin.interface.encodeFunctionData('upgradeAndCall', [
            gerL2Address,
            impGER,
            newGerFactory.interface.encodeFunctionData('initialize(address,address)', [
                globalExitRootUpdater,
                globalExitRootRemover,
            ]),
        ]), // data
        ethers.ZeroHash, // predecessor
        salt, // salt
    );
    logger.info('scheduleData & executeData');
    // Schedule operation
    const scheduleData = timelockContractFactory.interface.encodeFunctionData('scheduleBatch', [
        [operationBridge.target, operationGER.target],
        [operationBridge.value, operationGER.value],
        [operationBridge.data, operationGER.data],
        ethers.ZeroHash, // predecessor
        salt, // salt
        timelockDelay,
    ]);

    // Execute operation
    const executeData = timelockContractFactory.interface.encodeFunctionData('executeBatch', [
        [operationBridge.target, operationGER.target],
        [operationBridge.value, operationGER.value],
        [operationBridge.data, operationGER.data],
        ethers.ZeroHash, // predecessor
        salt, // salt
    ]);

    logger.info({ scheduleData });
    logger.info({ executeData });

    // Get current block number, used in the shallow fork tests
    const blockNumber = await ethers.provider.getBlockNumber();
    outputJson = {
        scheduleData,
        executeData,
        timelockContractAddress: timelockAddress,
        implementationDeployBlockNumber: blockNumber,
        bridgeImplementationAddress: impBridge,
        GERImplementationAddress: impGER,
        inputs: {
            bridgeManager,
            proxiedTokensManagerAddress,
            emergencyBridgePauserAddress,
            emergencyBridgeUnpauserAddress,
            globalExitRootUpdater,
            globalExitRootRemover,
            bridgeL2Address,
            gerL2Address,
        },
    };

    // Decode the scheduleData for better readability
    const objectDecoded = await decodeScheduleData(scheduleData, proxyAdmin);
    (outputJson as any).decodedScheduleData = objectDecoded;

    fs.writeFileSync(pathOutputJson, JSON.stringify(outputJson, null, 1));
    logger.info(`Output saved to: ${pathOutputJson}`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
