/* eslint-disable no-await-in-loop, no-use-before-define, no-lonely-if */
/* eslint-disable no-console, no-inner-declarations, no-undef, import/no-unresolved, no-restricted-syntax */
import { expect } from 'chai';
import path = require('path');
import fs from 'fs';

import * as dotenv from 'dotenv';
import { ethers, upgrades } from 'hardhat';
import { time, reset, setBalance, mine } from '@nomicfoundation/hardhat-network-helpers';
import {
    PolygonZkEVMTimelock,
    AgglayerGERL2,
    AgglayerBridgeL2,
    PolygonZkEVMBridgeV2Pessimistic,
    LegacyAgglayerGERL2,
} from '../../../typechain-types';
import upgradeParams from '../upgrade_parameters.json';
import upgradeOutput from '../upgrade_output.json';
import { logger } from '../../../src/logger';
import { checkParams } from '../../../src/utils';
import { ProxyAdmin } from '../../../typechain-types/@openzeppelin/contracts4/proxy/transparent';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

// Default paths for tokens and LBT files (generated by upgradeEtrogToSovereign.ts in parent folder)
const TOKENS_FILE_PATH = path.join(__dirname, '../tokens.json');
const LBT_FILE_PATH = path.join(__dirname, '../LBT.json');

async function main() {
    // Assert upgrade version
    const BRIDGE_SOVEREIGN_VERSION = 'v1.2.0';
    const GER_VERSION = 'v1.0.0';
    const mandatoryParameters = ['timelockAdminAddress', 'rpc'];
    checkParams(upgradeParams.forkParams, mandatoryParameters);
    const { rpc } = upgradeParams.forkParams;

    // hard fork
    logger.info(`Shadow forking ${rpc}`);
    try {
        await reset(rpc, upgradeOutput.implementationDeployBlockNumber);
        await mine();
    } catch (e) {
        console.log(e);
    }

    logger.info(`Shadow forked block number: ${await ethers.provider.getBlockNumber()}`);

    const bridgeImplAddress = upgradeOutput.bridgeImplementationAddress;
    const gerImplAddress = upgradeOutput.GERImplementationAddress;

    // Check implementations exist
    const bridgeImpCode = await ethers.provider.getCode(bridgeImplAddress);
    expect(bridgeImpCode.length).to.be.greaterThan(2);
    const gerImpCode = await ethers.provider.getCode(gerImplAddress);
    expect(gerImpCode.length).to.be.greaterThan(2);

    // Check timelock contract
    const { bridgeL2Address } = upgradeOutput.inputs;
    const { gerL2Address } = upgradeOutput.inputs;
    const proxyAdminAddress = await upgrades.erc1967.getAdminAddress(bridgeL2Address);
    const proxyAdminFactory = await ethers.getContractFactory(
        '@openzeppelin/contracts4/proxy/transparent/ProxyAdmin.sol:ProxyAdmin',
    );
    const proxyAdmin = proxyAdminFactory.attach(proxyAdminAddress) as ProxyAdmin;
    const ownerAddress = await proxyAdmin.owner();
    expect(upgradeOutput.timelockContractAddress).to.be.equal(ownerAddress);
    logger.info('✓ proxy admin role is same as upgrade output file timelock address');

    // Check proposed timelock admin address has proposer and executor role
    const timelockContractFactory = await ethers.getContractFactory('PolygonZkEVMTimelock');
    const timelockContract = (await timelockContractFactory.attach(ownerAddress)) as PolygonZkEVMTimelock;
    const PROPOSER_ROLE = ethers.id('PROPOSER_ROLE');
    const EXECUTOR_ROLE = ethers.id('EXECUTOR_ROLE');
    const proposerRoleAddress = upgradeParams.forkParams.timelockAdminAddress;
    const hasProposerRole = await timelockContract.hasRole(PROPOSER_ROLE, proposerRoleAddress);
    const hasExecutorRole = await timelockContract.hasRole(EXECUTOR_ROLE, proposerRoleAddress);

    console.log(proposerRoleAddress);
    if (!hasProposerRole || !hasExecutorRole) {
        throw new Error('Timelock admin address does not have proposer and executor role');
    }
    logger.info(`Proposer/executor timelock role address: ${proposerRoleAddress}`);
    await ethers.provider.send('hardhat_impersonateAccount', [proposerRoleAddress]);
    const proposerRoleSigner = await ethers.getSigner(proposerRoleAddress as any);
    await setBalance(proposerRoleAddress, 100n ** 18n);
    logger.info(`✓ Funded proposer account ${proposerRoleAddress}`);

    // get current storage values before upgrade
    const polygonZkEVMBridgeL2 = await ethers.getContractFactory('PolygonZkEVMBridgeV2Pessimistic');
    const bridgeOldContract = polygonZkEVMBridgeL2.attach(bridgeL2Address) as PolygonZkEVMBridgeV2Pessimistic;
    const bridgeLastUpdatedDepositCount = await bridgeOldContract.lastUpdatedDepositCount();
    const bridgeRollupManager = await bridgeOldContract.polygonRollupManager();
    const bridgeGasTokenAddress = await bridgeOldContract.gasTokenAddress();
    const bridgeGasTokenNetwork = await bridgeOldContract.gasTokenNetwork();
    const bridgeGasTokenMetadata = await bridgeOldContract.gasTokenMetadata();

    const polygonZkEVMGERL2 = await ethers.getContractFactory('LegacyAgglayerGERL2');
    const gerOldContract = polygonZkEVMGERL2.attach(gerL2Address) as LegacyAgglayerGERL2;
    const gerBridgeAddress = await gerOldContract.bridgeAddress();

    // Send schedule transaction
    const txScheduleUpgrade = {
        to: upgradeOutput.timelockContractAddress,
        data: upgradeOutput.scheduleData,
    };
    await (await proposerRoleSigner.sendTransaction(txScheduleUpgrade)).wait();

    logger.info('✓ Sent schedule transaction');

    // Increase time to bypass the timelock delay
    const timelockDelay = upgradeOutput.decodedScheduleData.delay;
    await time.increase(Number(timelockDelay));
    logger.info(`✓ Increase time ${timelockDelay} seconds to bypass timelock delay`);

    // Send execute transaction
    const txExecuteUpgrade = {
        to: upgradeOutput.timelockContractAddress,
        data: upgradeOutput.executeData,
    };
    await (await proposerRoleSigner.sendTransaction(txExecuteUpgrade)).wait();
    logger.info(`✓ Sent execute transaction`);

    // Check ger params after upgrade
    const agglayerGERL2Factory = await ethers.getContractFactory('AgglayerGERL2');
    const gerL2Contract = agglayerGERL2Factory.attach(gerL2Address) as AgglayerGERL2;
    expect(await gerL2Contract.globalExitRootUpdater()).to.equal(upgradeParams.ger_initParams.globalExitRootUpdater);
    expect(await gerL2Contract.globalExitRootRemover()).to.equal(upgradeParams.ger_initParams.globalExitRootRemover);
    expect(await gerL2Contract.GER_SOVEREIGN_VERSION()).to.equal(GER_VERSION);
    expect(await gerL2Contract.bridgeAddress()).to.equal(gerBridgeAddress);

    logger.info(`✓ Checked AgglayerGERL2 contract storage parameters`);

    // Check bridge params after upgrade
    const bridgeFactory = await ethers.getContractFactory('AgglayerBridgeL2');
    const bridgeContract = bridgeFactory.attach(bridgeL2Address) as AgglayerBridgeL2;
    expect(await bridgeContract.version()).to.equal(BRIDGE_SOVEREIGN_VERSION);
    expect((await bridgeContract.globalExitRootManager()).toLowerCase()).to.equal(gerL2Address.toLowerCase());
    expect(await bridgeContract.lastUpdatedDepositCount()).to.equal(bridgeLastUpdatedDepositCount);
    expect(await bridgeContract.polygonRollupManager()).to.equal(bridgeRollupManager);
    expect(await bridgeContract.gasTokenAddress()).to.equal(bridgeGasTokenAddress);
    expect(await bridgeContract.gasTokenNetwork()).to.equal(bridgeGasTokenNetwork);
    expect(await bridgeContract.gasTokenMetadata()).to.equal(bridgeGasTokenMetadata);
    expect(await bridgeContract.emergencyBridgePauser()).to.equal(
        upgradeParams.bridge_initParams.emergencyBridgePauserAddress,
    );
    expect(await bridgeContract.emergencyBridgeUnpauser()).to.equal(
        upgradeParams.bridge_initParams.emergencyBridgeUnpauserAddress,
    );

    // WARNING: with changes in tokens wrapped totalSupply, this test may fail
    // Read tokens.json and LBT.json from the parent folder (generated by upgradeEtrogToSovereign.ts)

    // Read tokens.json (used for initialization)
    const tokensData = JSON.parse(fs.readFileSync(TOKENS_FILE_PATH, 'utf8'));
    if (!tokensData.initNativeSupply || !tokensData.tokenAddresses) {
        throw new Error('Invalid tokens.json format. Expected object with initNativeSupply and tokenAddresses fields.');
    }

    // Read LBT.json (full balance tree with all details)
    const lbtData = JSON.parse(fs.readFileSync(LBT_FILE_PATH, 'utf8'));
    if (!Array.isArray(lbtData)) {
        throw new Error('Invalid LBT.json format. Expected array of objects.');
    }

    // Create a map of wrappedTokenAddress -> LBT entry for quick lookup
    // Include all entries including native token (ZeroAddress) as it IS in the LBT tree
    const lbtMap = new Map<string, { originNetwork: string; originTokenAddress: string; balance: string }>();
    for (const entry of lbtData) {
        lbtMap.set(entry.wrappedTokenAddress.toLowerCase(), {
            originNetwork: entry.originNetwork,
            originTokenAddress: entry.originTokenAddress,
            balance: entry.balance,
        });
    }

    // Verify that all wrappedTokenAddresses from tokens.json exist in LBT.json
    const { tokenAddresses } = tokensData;
    logger.info(`Verifying LBT for ${tokenAddresses.length} wrapped tokens...`);

    for (const wrappedTokenAddress of tokenAddresses) {
        const wrappedTokenLower = wrappedTokenAddress.toLowerCase();
        const lbtEntry = lbtMap.get(wrappedTokenLower);

        if (!lbtEntry) {
            throw new Error(`Wrapped token ${wrappedTokenAddress} from tokens.json not found in LBT.json`);
        }

        // Verify balance in local balance tree matches LBT.json
        const tokenInfoHash = ethers.solidityPackedKeccak256(
            ['uint32', 'address'],
            [lbtEntry.originNetwork, lbtEntry.originTokenAddress],
        );
        const lbtBalance = await bridgeContract.localBalanceTree(tokenInfoHash);
        expect(lbtEntry.balance).to.equal(lbtBalance.toString());
    }
    logger.info(`✓ Checked LBT parameters`);

    logger.info(`✓ Checked AgglayerBridgeL2 contract storage parameters`);
    logger.info('Finished shadow fork upgrade');
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
