// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import {ClaimCompressor} from "contracts/utils/ClaimCompressor.sol";
import {ProxyAdmin} from "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import {TransparentUpgradeableProxy, ITransparentUpgradeableProxy} from "@openzeppelin/contracts5/proxy/transparent/TransparentUpgradeableProxy.sol";

abstract contract ClaimCompressorDeployer is Script {
    ClaimCompressor internal claimCompressor;
    ProxyAdmin internal claimCompressorProxyAdmin;
    address internal claimCompressorImplementation;

    function deployClaimCompressorTransparent(
        address proxyAdminOwner,
        address __bridgeAddress,
        uint32 __networkID
    )
        internal
        returns (address implementation, address proxyAdmin, address proxy)
    {
        bytes memory initData = "";

        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));

        claimCompressorImplementation = address(
            new ClaimCompressor(__bridgeAddress, __networkID)
        );
        claimCompressor = ClaimCompressor(
            address(
                new TransparentUpgradeableProxy(
                    claimCompressorImplementation,
                    proxyAdminOwner,
                    initData
                )
            )
        );

        vm.stopBroadcast();

        claimCompressorProxyAdmin = ProxyAdmin(
            address(
                uint160(
                    uint256(
                        vm.load(
                            address(claimCompressor),
                            hex"b53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103"
                        )
                    )
                )
            )
        );

        return (
            claimCompressorImplementation,
            address(claimCompressorProxyAdmin),
            address(claimCompressor)
        );
    }

    function deployClaimCompressorImplementation(
        address __bridgeAddress,
        uint32 __networkID
    ) internal returns (address implementation) {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(
            new ClaimCompressor(__bridgeAddress, __networkID)
        );
        vm.stopBroadcast();
    }
}
