// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "contracts/mocks/ERC20PermitMock.sol";

abstract contract ERC20PermitMockDeployer is Script {
    function deployERC20PermitMockImplementation(
        string memory name,
        string memory symbol,
        address initialAccount,
        uint256 initialBalance
    ) internal returns (address implementation) {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(
            new ERC20PermitMock(name, symbol, initialAccount, initialBalance)
        );
        vm.stopBroadcast();
    }
}
