// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "contracts/verifiers/FflonkVerifier.sol";
import {ProxyAdmin} from "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import {TransparentUpgradeableProxy, ITransparentUpgradeableProxy} from "@openzeppelin/contracts5/proxy/transparent/TransparentUpgradeableProxy.sol";

abstract contract FflonkVerifierDeployer is Script {
    FflonkVerifier internal fflonkVerifier;
    ProxyAdmin internal fflonkVerifierProxyAdmin;
    address internal fflonkVerifierImplementation;

    function deployFflonkVerifierTransparent(
        address proxyAdminOwner
    )
        internal
        returns (address implementation, address proxyAdmin, address proxy)
    {
        bytes memory initData = "";

        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));

        fflonkVerifierImplementation = address(new FflonkVerifier());
        fflonkVerifier = FflonkVerifier(
            address(
                new TransparentUpgradeableProxy(
                    fflonkVerifierImplementation,
                    proxyAdminOwner,
                    initData
                )
            )
        );

        vm.stopBroadcast();

        fflonkVerifierProxyAdmin = ProxyAdmin(
            address(
                uint160(
                    uint256(
                        vm.load(
                            address(fflonkVerifier),
                            hex"b53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103"
                        )
                    )
                )
            )
        );

        return (
            fflonkVerifierImplementation,
            address(fflonkVerifierProxyAdmin),
            address(fflonkVerifier)
        );
    }

    function deployFflonkVerifierImplementation()
        internal
        returns (address implementation)
    {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(new FflonkVerifier());
        vm.stopBroadcast();
    }
}
