// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "contracts/deployment/PolygonZkEVMDeployer.sol";

abstract contract PolygonZkEVMDeployerDeployer is Script {
    PolygonZkEVMDeployer internal polygonZkEVMDeployer;

    function deployPolygonZkEVMDeployerImplementation(address _owner) internal returns (address implementation) {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(new PolygonZkEVMDeployer(_owner));
        vm.stopBroadcast();
    }
}
