// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "contracts/mocks/PolygonRollupManagerEmptyMock.sol";
import {ProxyAdmin} from "@openzeppelin/contracts5/proxy/transparent/ProxyAdmin.sol";
import {TransparentUpgradeableProxy, ITransparentUpgradeableProxy} from "@openzeppelin/contracts5/proxy/transparent/TransparentUpgradeableProxy.sol";

abstract contract PolygonRollupManagerEmptyMockDeployer is Script {
    PolygonRollupManagerEmptyMock internal polygonRollupManagerEmptyMock;
    ProxyAdmin internal polygonRollupManagerEmptyMockProxyAdmin;
    address internal polygonRollupManagerEmptyMockImplementation;

    function deployPolygonRollupManagerEmptyMockTransparent(
        address proxyAdminOwner
    )
        internal
        returns (address implementation, address proxyAdmin, address proxy)
    {
        bytes memory initData = "";

        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));

        polygonRollupManagerEmptyMockImplementation = address(
            new PolygonRollupManagerEmptyMock()
        );
        polygonRollupManagerEmptyMock = PolygonRollupManagerEmptyMock(
            address(
                new TransparentUpgradeableProxy(
                    polygonRollupManagerEmptyMockImplementation,
                    proxyAdminOwner,
                    initData
                )
            )
        );

        vm.stopBroadcast();

        polygonRollupManagerEmptyMockProxyAdmin = ProxyAdmin(
            address(
                uint160(
                    uint256(
                        vm.load(
                            address(polygonRollupManagerEmptyMock),
                            hex"b53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103"
                        )
                    )
                )
            )
        );

        return (
            polygonRollupManagerEmptyMockImplementation,
            address(polygonRollupManagerEmptyMockProxyAdmin),
            address(polygonRollupManagerEmptyMock)
        );
    }

    function deployPolygonRollupManagerEmptyMockImplementation()
        internal
        returns (address implementation)
    {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(new PolygonRollupManagerEmptyMock());
        vm.stopBroadcast();
    }
}
