// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "contracts/mocks/VerifierRollupHelperMock.sol";
import {ProxyAdmin} from "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import {TransparentUpgradeableProxy, ITransparentUpgradeableProxy} from "@openzeppelin/contracts5/proxy/transparent/TransparentUpgradeableProxy.sol";

abstract contract VerifierRollupHelperMockDeployer is Script {
    VerifierRollupHelperMock internal verifierRollupHelperMock;
    ProxyAdmin internal verifierRollupHelperMockProxyAdmin;
    address internal verifierRollupHelperMockImplementation;

    function deployVerifierRollupHelperMockTransparent(
        address proxyAdminOwner
    )
        internal
        returns (address implementation, address proxyAdmin, address proxy)
    {
        bytes memory initData = "";

        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));

        verifierRollupHelperMockImplementation = address(
            new VerifierRollupHelperMock()
        );
        verifierRollupHelperMock = VerifierRollupHelperMock(
            address(
                new TransparentUpgradeableProxy(
                    verifierRollupHelperMockImplementation,
                    proxyAdminOwner,
                    initData
                )
            )
        );

        vm.stopBroadcast();

        verifierRollupHelperMockProxyAdmin = ProxyAdmin(
            address(
                uint160(
                    uint256(
                        vm.load(
                            address(verifierRollupHelperMock),
                            hex"b53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103"
                        )
                    )
                )
            )
        );

        return (
            verifierRollupHelperMockImplementation,
            address(verifierRollupHelperMockProxyAdmin),
            address(verifierRollupHelperMock)
        );
    }

    function deployVerifierRollupHelperMockImplementation()
        internal
        returns (address implementation)
    {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        implementation = address(new VerifierRollupHelperMock());
        vm.stopBroadcast();
    }
}
